### ISSUE TITLE
building locally/appimage?

### ISSUE THREAD

**Issue by kaii-lb** [SalaniLeo/Forecast#26]
if a user doesn't want to/can't install through flatpak, how can they build the app locally?

**Comment by SalaniLeo** [comment]
sorry for this late reply, for now there isn't any way to install Forecast as non flatpak. I was working on adding the option to compile as appimage but I stopped working on it because of a bug in gtk that makes my app crash, and I can't release a new version. I opened an issue here describing the gtk issue. I hope a new version of gtk with the fix releases soon so I can work on the app again.

**Comment by kaii-lb** [comment]
no worries! i'll check out the issue as it seems really interesting, thanks for the support!
