### ISSUE TITLE
Remove Left Anchor for Weekly Forecast

### ISSUE THREAD

**Issue by LinuxinaBit** [SalaniLeo/Forecast#38]
Nice weather app!
There's just one (actually pretty minor) thing I think needs to be changed.
I believe anchoring the Weekly Forecast to the left side of the window is a missed opportunity that also results in an imbalanced feeling app.
Example:
![image](https://github.com/SalaniLeo/Forecast/assets/105567407/ea484252-03fb-4a5b-b6a3-b8c6c63810de)
![image](https://github.com/SalaniLeo/Forecast/assets/105567407/6ae7b2d7-1ae2-4dcd-b521-23f7903070e7)
I believe utilizing whatever [Flexbox-like](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) technology GTK provides would allow the app to feel more balanced at any window size.
This also could allow for a responsive app that automatically realigns into a vertical scroll-able layout for mobile devices and devices with small displays.
Thank you for considering this change, and I really like the app :)

**Comment by SalaniLeo** [comment]
Thanks for the advice, I already tried to use a flexbox, but the issue was that the window height would be stuck to the minumum required to move the left side below the right one so I decided to not include it in this release. For the next release I already have in mind a way to make this app small screen friendly by using an Adw.Breakpoint. Thanks again for contributing!
